-- Secondary indexes for the canonical MySQL 8 bundle.

CREATE INDEX idx_sites_tenant_status ON sites (tenant_id, status);
CREATE INDEX idx_users_tenant_role_status ON users (tenant_id, role, status);
CREATE INDEX idx_auth_user_expires ON auth_sessions (user_id, expires_at);
CREATE INDEX idx_sources_site_type ON sources (site_id, source_type, status);
CREATE INDEX idx_idemp_expires ON ingress_idempotency (expires_at);
CREATE INDEX idx_rules_tenant_enabled ON rules (tenant_id, enabled, priority_order);
CREATE INDEX idx_events_tenant_state_priority ON events (tenant_id, state, priority DESC, occurred_at DESC);
CREATE INDEX idx_events_tenant_filters ON events (tenant_id, site_id, zone_code, event_type, severity, occurred_at DESC);
CREATE INDEX idx_events_plate_time ON events (tenant_id, plate, occurred_at DESC);
CREATE INDEX idx_events_request ON events (request_id);
CREATE INDEX idx_event_evidence_event ON event_evidence (event_id);
CREATE INDEX idx_event_timeline_event_time ON event_timeline (event_id, occurred_at ASC);
CREATE INDEX idx_event_timeline_tenant_time ON event_timeline (tenant_id, occurred_at DESC);
CREATE INDEX idx_adm_tenant_entry ON admissions (tenant_id, entry_at DESC);
CREATE INDEX idx_adm_tenant_plate_entry ON admissions (tenant_id, plate, entry_at DESC);
CREATE INDEX idx_adm_review ON admissions (tenant_id, review_required, entry_at DESC);
CREATE INDEX idx_spd_evt_tenant_time ON speed_events (tenant_id, occurred_at DESC);
CREATE INDEX idx_spd_evt_tenant_plate ON speed_events (tenant_id, plate, occurred_at DESC);
CREATE INDEX idx_spd_ev_event ON speed_event_evidence (speed_event_id);
CREATE INDEX idx_spd_case_filters ON speed_cases (tenant_id, site_id, state, correlation_status, opened_at);
CREATE INDEX idx_spd_case_plate_time ON speed_cases (tenant_id, opened_at);
CREATE INDEX idx_notif_filters ON notifications (tenant_id, site_id, channel, status, created_at);
CREATE INDEX idx_notif_event ON notifications (event_id);
CREATE INDEX idx_notif_case ON notifications (speed_case_id);
CREATE INDEX idx_connector_last_heartbeat ON edge_connectors (tenant_id, site_id, last_heartbeat_at);
CREATE INDEX idx_health_status ON device_health_status (tenant_id, site_id, status, last_check_at);
CREATE INDEX idx_health_incident_filters ON health_incidents (tenant_id, site_id, status, severity, opened_at);
CREATE INDEX idx_audit_tenant_time ON api_audit_log (tenant_id, created_at);
CREATE INDEX idx_audit_entity ON api_audit_log (tenant_id, entity_type, entity_id);
CREATE INDEX idx_audit_actor ON api_audit_log (tenant_id, actor_user_id, created_at);
