// Mock data for TNS Track MVP demonstration
import type { Alert, Zone, Tenant, VehicleEntry, Rule, User, Camera, NVR, PlateSource } from './types'
import { buildAlertsFromRuleSeeds, type RuleAlertSeed } from './mock-alert-builder'

// Zonas mock
export const MOCK_ZONES: Zone[] = [
  { id: 1, name: 'Entrada Principal', description: 'Acceso vehicular y peatonal principal', priority: 'critica', tenant_id: 1, active: true },
  { id: 2, name: 'Zona Industrial A', description: 'Bodegas y naves industriales sector norte', priority: 'alta', tenant_id: 1, active: true },
  { id: 3, name: 'Zona Industrial B', description: 'Bodegas y naves industriales sector sur', priority: 'alta', tenant_id: 1, active: true },
  { id: 4, name: 'Zona Logistica', description: 'Area de carga y descarga', priority: 'alta', tenant_id: 1, active: true },
  { id: 5, name: 'Estacionamiento', description: 'Estacionamiento general de vehiculos', priority: 'media', tenant_id: 1, active: true },
  { id: 6, name: 'Perimetro Norte', description: 'Cerco perimetral sector norte', priority: 'critica', tenant_id: 1, active: true },
  { id: 7, name: 'Perimetro Sur', description: 'Cerco perimetral sector sur', priority: 'critica', tenant_id: 1, active: true },
  { id: 8, name: 'Area Administrativa', description: 'Oficinas y administracion', priority: 'media', tenant_id: 1, active: true },
]

// Empresas (Tenants) mock
export const MOCK_TENANTS: Tenant[] = [
  { id: 1, rut: '76.123.456-7', legal_name: 'Agrolivo SpA', commercial_name: 'Agrolivo', active: true },
  { id: 2, rut: '76.234.567-8', legal_name: 'Transportes del Valle Ltda.', commercial_name: 'Transportes del Valle', active: true },
  { id: 3, rut: '76.345.678-9', legal_name: 'Logistica Central S.A.', commercial_name: 'LogiCentral', active: true },
  { id: 4, rut: '76.456.789-0', legal_name: 'Distribuidora Norte Ltda.', commercial_name: 'DisNorte', active: true },
  { id: 5, rut: '76.567.890-1', legal_name: 'Alimentos del Sur SpA', commercial_name: 'AliSur', active: true },
  { id: 6, rut: '76.678.901-2', legal_name: 'Metalurgica Industrial S.A.', commercial_name: 'MetalInd', active: true },
  { id: 7, rut: '76.789.012-3', legal_name: 'Comercial Importadora Ltda.', commercial_name: 'ComImport', active: true },
  { id: 8, rut: '76.890.123-4', legal_name: 'Servicios Tecnicos SpA', commercial_name: 'ServTec', active: true },
]

// Camaras mock (antes de reglas y alertas derivadas)
export const MOCK_CAMERAS: Camera[] = [
  { id: 1, name: 'CAM-PER-N01', ip: '192.168.1.101', channel: 1, nvr_id: 1, zone_id: 6, active: true },
  { id: 2, name: 'CAM-EST-01', ip: '192.168.1.102', channel: 2, nvr_id: 1, zone_id: 5, active: true },
  { id: 3, name: 'CAM-IND-A01', ip: '192.168.1.103', channel: 3, nvr_id: 1, zone_id: 2, active: true },
  { id: 4, name: 'CAM-ENT-01', ip: '192.168.1.104', channel: 4, nvr_id: 1, zone_id: 1, active: true },
  { id: 5, name: 'CAM-LOG-01', ip: '192.168.1.105', channel: 5, nvr_id: 2, zone_id: 4, active: true },
  { id: 6, name: 'CAM-IND-B01', ip: '192.168.1.106', channel: 6, nvr_id: 2, zone_id: 3, active: true },
  { id: 7, name: 'CAM-EST-02', ip: '192.168.1.107', channel: 7, nvr_id: 2, zone_id: 5, active: true },
  { id: 8, name: 'CAM-PER-S01', ip: '192.168.1.108', channel: 8, nvr_id: 2, zone_id: 7, active: true },
]

// Ingresos vehiculares mock
export const MOCK_VEHICLE_ENTRIES: VehicleEntry[] = [
  {
    id: 1,
    plate: 'BCDF-12',
    plate_normalized: 'BCDF12',
    declared_driver_name: 'Juan Perez',
    declared_driver_id: '12.345.678-9',
    tenant_id: 2,
    tenant: MOCK_TENANTS[1],
    destination_text: 'Bodega 3 - Descarga mercaderia',
    vehicle_type: 'camion',
    entry_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    exit_at: null,
    registered_by: '1',
    observations: 'Transporta materiales de construccion',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    plate_source: 'hybrid',
    anpr_confidence: 96,
  },
  {
    id: 2,
    plate: 'WXYZ-98',
    plate_normalized: 'WXYZ98',
    declared_driver_name: 'Maria Gonzalez',
    declared_driver_id: '13.456.789-0',
    tenant_id: 3,
    tenant: MOCK_TENANTS[2],
    destination_text: 'Oficinas administrativas',
    vehicle_type: 'particular',
    entry_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    exit_at: null,
    registered_by: '1',
    observations: null,
    created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    plate_source: 'anpr',
    anpr_confidence: 92,
  },
  {
    id: 3,
    plate: 'LMNO-45',
    plate_normalized: 'LMNO45',
    declared_driver_name: 'Pedro Martinez',
    declared_driver_id: '14.567.890-1',
    tenant_id: 4,
    tenant: MOCK_TENANTS[3],
    destination_text: 'Bodega 7 - Retiro productos',
    vehicle_type: 'utilitario',
    entry_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    exit_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    registered_by: '1',
    observations: null,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    plate_source: 'manual',
  },
  {
    id: 4,
    plate: 'HIJK-67',
    plate_normalized: 'HIJK67',
    declared_driver_name: 'Ana Silva',
    declared_driver_id: '15.678.901-2',
    tenant_id: 5,
    tenant: MOCK_TENANTS[4],
    destination_text: 'Area de produccion',
    vehicle_type: 'particular',
    entry_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    exit_at: null,
    registered_by: '1',
    observations: null,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    plate_source: 'hybrid',
    anpr_confidence: 88,
  },
  {
    id: 5,
    plate: 'QRST-23',
    plate_normalized: 'QRST23',
    declared_driver_name: 'Roberto Diaz',
    declared_driver_id: '16.789.012-3',
    tenant_id: 6,
    tenant: MOCK_TENANTS[5],
    destination_text: 'Bodega 10 - Mantenimiento',
    vehicle_type: 'camion',
    entry_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    exit_at: null,
    registered_by: '1',
    observations: 'Equipo de mantenimiento',
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    plate_source: 'anpr',
    anpr_confidence: 94,
  },
]

// Reglas mock — codigos de evento reales suscribibles via API Dahua
const MOCK_RULES_BASE: Rule[] = [
  {
    id: 1,
    name: 'Intrusion perimetral nocturna',
    description: 'Cruce de linea o intrusion en cerco perimetral durante horario nocturno',
    event_codes: ['CrossLineDetection', 'CrossRegionDetection'],
    event_code_pattern: 'CrossLineDetection',
    criticality: 'critica',
    zone_id: 6,
    zone: MOCK_ZONES[5],
    time_from: '22:00',
    time_to: '06:00',
    priority_popup: true,
    notify_admin: true,
    record_evidence: true,
    can_escalate: true,
    escalation_roles: ['responsable_seguridad', 'admin_parque'],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 2,
    name: 'Merodeo perimetral',
    description: 'Persona deambulando junto al cerco perimetral (loitering)',
    event_codes: ['WanderDetection'],
    event_code_pattern: 'WanderDetection',
    criticality: 'alta',
    zone_id: 7,
    zone: MOCK_ZONES[6],
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: true,
    notify_admin: true,
    can_escalate: true,
    escalation_roles: ['responsable_seguridad', 'admin_parque'],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 3,
    name: 'Persona fuera de horario (IA)',
    description: 'Movimiento humano detectado por IA en zona industrial fuera de horario laboral',
    event_codes: ['SmartMotionHuman'],
    event_code_pattern: 'SmartMotionHuman',
    criticality: 'media',
    zone_id: 2,
    zone: MOCK_ZONES[1],
    time_from: '20:00',
    time_to: '06:00',
    priority_popup: true,
    can_escalate: false,
    escalation_roles: [],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 4,
    name: 'Acceso no autorizado entrada',
    description: 'Entrada a zona restringida por la entrada principal',
    event_codes: ['CrossRegionDetection'],
    event_code_pattern: 'CrossRegionDetection',
    criticality: 'alta',
    zone_id: 1,
    zone: MOCK_ZONES[0],
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: true,
    notify_admin: true,
    can_escalate: true,
    escalation_roles: ['responsable_seguridad', 'admin_parque'],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 5,
    name: 'Objeto abandonado en transito',
    description: 'Deteccion de objetos abandonados en zonas de carga y descarga',
    event_codes: ['LeftDetection'],
    event_code_pattern: 'LeftDetection',
    criticality: 'media',
    zone_id: 4,
    zone: MOCK_ZONES[3],
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: true,
    can_escalate: false,
    escalation_roles: [],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 6,
    name: 'ANPR ingreso recepcion',
    description: 'Lectura de patente al ingreso por recepcion; alimenta el registro de ingresos',
    event_codes: ['TrafficJunction'],
    event_code_pattern: 'TrafficJunction',
    criticality: 'baja',
    zone_id: 1,
    zone: MOCK_ZONES[0],
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: false,
    record_evidence: true,
    can_escalate: false,
    escalation_roles: [],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 7,
    name: 'Exceso de velocidad Camino El Olivo',
    description: 'Vehiculo supera el limite de velocidad. Requiere camara ITC/LPR dedicada en Camino El Olivo.',
    event_codes: ['TrafficOverSpeed'],
    event_code_pattern: 'TrafficOverSpeed',
    criticality: 'alta',
    zone_id: null,
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: true,
    notify_admin: true,
    notify_tenant: true,
    record_evidence: true,
    can_escalate: true,
    escalation_roles: ['responsable_seguridad', 'admin_parque'],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 8,
    name: 'Camara cubierta / sabotaje',
    description: 'Camara tapada o manipulada (video blind) en cualquier zona',
    event_codes: ['VideoBlind'],
    event_code_pattern: 'VideoBlind',
    criticality: 'alta',
    zone_id: null,
    time_from: '00:00',
    time_to: '23:59',
    priority_popup: true,
    notify_admin: true,
    can_escalate: true,
    escalation_roles: ['responsable_seguridad', 'admin_parque'],
    enabled: true,
    tenant_id: 1,
  },
  {
    id: 9,
    name: 'Salud tecnica (perdida de senal)',
    description: 'Perdida de senal de video o falla de almacenamiento; alerta al equipo tecnico',
    event_codes: ['VideoLoss', 'StorageFailure'],
    event_code_pattern: 'VideoLoss',
    criticality: 'media',
    zone_id: null,
    time_from: '00:00',
    time_to: '23:59',
    notify_admin: true,
    can_escalate: false,
    escalation_roles: [],
    enabled: false,
    tenant_id: 1,
  },
]

export const MOCK_RULES: Rule[] = MOCK_RULES_BASE.map((rule) => ({
  ...rule,
  rule_id: rule.rule_id ?? `RG${String(rule.id).padStart(24, '0')}`,
  rule_code: rule.rule_code ?? `Regla-${String(rule.id).padStart(4, '0')}`,
  notify_push_roles:
    rule.notify_push_roles ??
    (rule.notify_admin ? ['responsable_seguridad', 'admin_parque'] : []),
  escalation_roles:
    rule.can_escalate && rule.escalation_roles?.length
      ? ['responsable_seguridad', 'admin_parque', 'supervisor']
      : rule.escalation_roles ?? [],
}))

// Usuarios mock
export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'admin@agrolivo.cl',
    nombre: 'Carlos Rodriguez',
    telefono: '+56 9 7743 2219',
    role: 'admin_parque',
    ultimaConexion: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    activo: true,
  },
  {
    id: '2',
    email: 'supervisor@agrolivo.cl',
    nombre: 'Maria Gonzalez',
    telefono: '+56 9 9103 5567',
    role: 'supervisor',
    ultimaConexion: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    activo: true,
  },
  {
    id: '3',
    email: 'operador@agrolivo.cl',
    nombre: 'Juan Perez',
    telefono: '+56 9 8765 4321',
    role: 'vigilante',
    ultimaConexion: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    activo: true,
  },
  {
    id: '4',
    email: 'recepcionista@agrolivo.cl',
    nombre: 'Ana Silva',
    telefono: '+56 9 7654 3210',
    role: 'recepcionista',
    ultimaConexion: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    activo: true,
  },
  {
    id: '5',
    email: 'tecnico@agrolivo.cl',
    nombre: 'Roberto Diaz',
    telefono: '+56 2 2891 0045',
    role: 'tecnico',
    ultimaConexion: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    activo: false,
  },
  {
    id: '6',
    email: 'seguridad@agrolivo.cl',
    nombre: 'Patricia Morales',
    telefono: '+56 9 8821 4430',
    role: 'responsable_seguridad',
    ultimaConexion: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    activo: true,
  },
]

/** Alertas live: derivadas de reglas activas (ultimos minutos) */
const LIVE_RULE_SEEDS: RuleAlertSeed[] = [
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'pendiente', minutesAgo: 2 },
  { ruleId: 4, status: 'pendiente', minutesAgo: 4, note: 'Peaton sin credencial en torniquete' },
  { ruleId: 7, status: 'pendiente', minutesAgo: 5, zone_id: 5, plate: 'BCDF-12' },
  { ruleId: 5, status: 'pendiente', minutesAgo: 8, note: 'Pallet en pasillo de despacho' },
  { ruleId: 3, status: 'pendiente', minutesAgo: 10, note: 'Movimiento detectado en bodega fuera de horario' },
  { ruleId: 2, status: 'pendiente', minutesAgo: 12, note: 'Deambulacion junto al cerco sur' },
  { ruleId: 8, status: 'pendiente', minutesAgo: 15, zone_id: 2, note: 'Obstruccion parcial de lente' },
  { ruleId: 2, status: 'en_revision', minutesAgo: 20, assigned_to: 'Carlos Rodriguez', note: 'Guardia verificando en sitio' },
  { ruleId: 6, status: 'resuelta', minutesAgo: 45, note: 'Patente BCDF-12 correlacionada con ingreso' },
  { ruleId: 2, status: 'resuelta', minutesAgo: 90, resolution_notes: 'Falsa alarma — animal silvestre' },
]

/** Historico del dia: cada fila referencia una regla de MOCK_RULES; timestamps siempre en el pasado */
const HISTORICAL_RULE_SEEDS: RuleAlertSeed[] = [
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'resuelta', hour: 5, minute: 40, resolution_notes: 'Guardia de turno verifico — fauna' },
  { ruleId: 6, status: 'resuelta', hour: 6, minute: 45, note: 'Ingreso proveedor registrado en recepcion' },
  { ruleId: 4, status: 'resuelta', hour: 7, minute: 8, resolution_notes: 'Visitante registrado en recepcion' },
  { ruleId: 5, status: 'descartada', hour: 7, minute: 52, resolution_notes: 'Personal autorizado de logistica' },
  { ruleId: 7, status: 'resuelta', hour: 8, minute: 5, zone_id: 5, plate: 'KLMN-34', resolution_notes: 'Notificado al conductor' },
  { ruleId: 4, status: 'resuelta', hour: 8, minute: 41, note: 'Tarjeta de acceso vencida' },
  { ruleId: 5, status: 'resuelta', hour: 9, minute: 10 },
  { ruleId: 2, status: 'resuelta', hour: 9, minute: 33, resolution_notes: 'Falsa alarma — viento movio malla' },
  { ruleId: 3, status: 'resuelta', hour: 5, minute: 55, note: 'Operarios con turno autorizado' },
  { ruleId: 7, status: 'resuelta', hour: 10, minute: 7, zone_id: 5, plate: 'PQRS-78' },
  { ruleId: 4, status: 'resuelta', hour: 10, minute: 18 },
  { ruleId: 5, status: 'resuelta', hour: 10, minute: 34 },
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'escalada', hour: 11, minute: 3, resolution_notes: 'Escalada a supervisor — persona identificada' },
  { ruleId: 2, status: 'resuelta', hour: 11, minute: 44, assigned_to: 'Maria Gonzalez', resolution_notes: 'Operario en buen estado' },
  { ruleId: 4, status: 'resuelta', hour: 11, minute: 58 },
  { ruleId: 7, status: 'resuelta', hour: 12, minute: 6, zone_id: 5, plate: 'TUVW-11' },
  { ruleId: 5, status: 'resuelta', hour: 12, minute: 28, resolution_notes: 'Pertenencia de conductor identificado' },
  { ruleId: 4, status: 'resuelta', hour: 12, minute: 40 },
  { ruleId: 2, status: 'resuelta', hour: 13, minute: 2 },
  { ruleId: 5, status: 'resuelta', hour: 13, minute: 19, note: 'Personal de mantenimiento en muelle' },
  { ruleId: 7, status: 'resuelta', hour: 13, minute: 37, zone_id: 5, plate: 'XYZA-56' },
  { ruleId: 2, status: 'resuelta', hour: 13, minute: 51 },
  { ruleId: 4, status: 'resuelta', hour: 14, minute: 9 },
  { ruleId: 5, status: 'resuelta', hour: 14, minute: 26 },
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'resuelta', hour: 14, minute: 48 },
  { ruleId: 7, status: 'resuelta', hour: 15, minute: 52, zone_id: 5, plate: 'BCDE-90' },
  { ruleId: 4, status: 'resuelta', hour: 16, minute: 8 },
  { ruleId: 5, status: 'resuelta', hour: 16, minute: 24 },
  { ruleId: 2, status: 'resuelta', hour: 16, minute: 41, resolution_notes: 'Danio menor — mantenimiento notificado' },
  { ruleId: 3, status: 'resuelta', hour: 17, minute: 28 },
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'resuelta', hour: 18, minute: 14 },
  { ruleId: 3, status: 'resuelta', hour: 18, minute: 36 },
  { ruleId: 4, status: 'resuelta', hour: 19, minute: 2 },
  { ruleId: 7, status: 'resuelta', hour: 19, minute: 27, zone_id: 5, note: 'Camion de salida en rampa' },
  { ruleId: 2, status: 'resuelta', hour: 20, minute: 18, note: 'Ronda confirmo sector sur' },
  { ruleId: 3, status: 'resuelta', hour: 21, minute: 6, note: 'Puerta entreabierta cerrada por guardia' },
  { ruleId: 1, event_code: 'CrossLineDetection', status: 'resuelta', hour: 23, minute: 12 },
  { ruleId: 8, status: 'resuelta', hour: 10, minute: 22, zone_id: 3, note: 'CAM-IND-B01 — lente limpiado' },
]

const MOCK_ALERTS_LIVE = buildAlertsFromRuleSeeds(LIVE_RULE_SEEDS, 1, MOCK_RULES, MOCK_ZONES, MOCK_CAMERAS)
const MOCK_ALERTS_TODAY_HISTORICAL = buildAlertsFromRuleSeeds(
  HISTORICAL_RULE_SEEDS,
  100,
  MOCK_RULES,
  MOCK_ZONES,
  MOCK_CAMERAS
)

export const MOCK_ALERTS: Alert[] = [...MOCK_ALERTS_LIVE, ...MOCK_ALERTS_TODAY_HISTORICAL]

// NVRs mock
export const MOCK_NVRS: NVR[] = [
  { id: 1, name: 'NVR-Principal', ip: '192.168.1.10', port: 80, status: 'online', cameras_count: 4, tenant_id: 1 },
  { id: 2, name: 'NVR-Secundario', ip: '192.168.1.11', port: 80, status: 'online', cameras_count: 4, tenant_id: 1 },
]
